language: cpp
dist: focal
before_script:
- cd ../doxygen
- sudo apt install graphviz -y
- sudo apt install ./doxygen_1.8.19_amd64.deb
- doxygen --version
- cd ..
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
  provider: script
  skip_cleanup: true
  script:
   - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uazbyx:$BINTRAY_API_K "https://api.bintray.com/content/azbyx/azbyx/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"